name: MongoDB Pinger

on:
  schedule:
    - cron: "0 0 25 * *"
  workflow_dispatch: # Manual trigger button in GitHub Actions tab

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Install dependencies
        run: npm install
      
      - name: Build CLI
        run: npm run build
      
      - name: Run Mongo Pinger
        run: npm start
        env:
          DATABASE_URI: ${{ secrets.DATABASE_URI }}
